<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerKAdZ5bz\App_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerKAdZ5bz/App_KernelDevDebugContainer.php') {
    touch(__DIR__.'/ContainerKAdZ5bz.legacy');

    return;
}

if (!\class_exists(App_KernelDevDebugContainer::class, false)) {
    \class_alias(\ContainerKAdZ5bz\App_KernelDevDebugContainer::class, App_KernelDevDebugContainer::class, false);
}

return new \ContainerKAdZ5bz\App_KernelDevDebugContainer([
    'container.build_hash' => 'KAdZ5bz',
    'container.build_id' => '9e2c7124',
    'container.build_time' => 1670093811,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerKAdZ5bz');
