<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerYzO0CnB\App_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerYzO0CnB/App_KernelDevDebugContainer.php') {
    touch(__DIR__.'/ContainerYzO0CnB.legacy');

    return;
}

if (!\class_exists(App_KernelDevDebugContainer::class, false)) {
    \class_alias(\ContainerYzO0CnB\App_KernelDevDebugContainer::class, App_KernelDevDebugContainer::class, false);
}

return new \ContainerYzO0CnB\App_KernelDevDebugContainer([
    'container.build_hash' => 'YzO0CnB',
    'container.build_id' => '687eb8a9',
    'container.build_time' => 1669996466,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerYzO0CnB');
