<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerDhKGEhj\App_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerDhKGEhj/App_KernelDevDebugContainer.php') {
    touch(__DIR__.'/ContainerDhKGEhj.legacy');

    return;
}

if (!\class_exists(App_KernelDevDebugContainer::class, false)) {
    \class_alias(\ContainerDhKGEhj\App_KernelDevDebugContainer::class, App_KernelDevDebugContainer::class, false);
}

return new \ContainerDhKGEhj\App_KernelDevDebugContainer([
    'container.build_hash' => 'DhKGEhj',
    'container.build_id' => '81ad0a28',
    'container.build_time' => 1670169762,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerDhKGEhj');
